### ISSUE TITLE
The plugin doesn't work on windows 

### ISSUE THREAD

**Issue by myartings** [wetadigital/USDPluginExamples#44] opened 2023-06-25 13:17 UTC
### Description of Issue
Just follow the tutorial , build and install the plugin , when I run "usdview ./src/usdTri/scenes/triangle.usda" in cmd,  it says " ModuleNotFoundError: No module named 'usdpluginexamples'", "Load of usdpluginexamples.UsdviewTri for usdpluginexamples.UsdviewTri failed". The detail is below, I Don't have any idea about this issue. My USD version is 23.05, built in release. I Need help.
### Steps to Reproduce
1.  build and install plugin
2. set up environment variables for plugin
3. run usdview ./src/usdTri/scenes/triangle.usda in console

### System Information (OS, Hardware)
Windows 10
USD 23.05
python 3.10.5
cmake 3.24
visual studio 2022

### Build Flags

![image](https://github.com/wetadigital/USDPluginExamples/assets/4220108/d6160c90-7728-4cd4-a454-702bfe139bfd)

**Comment by myartings** [comment] 2023-06-26 02:46
sorry, I forget to add "${USDPLUGINEXAMPLES_INSTALL_ROOT}/lib/python" to PYTHONPATH. But the error still occur.
![image](https://github.com/wetadigital/USDPluginExamples/assets/4220108/f66339af-0b97-4af7-a172-34892ddcbbdd)

**Comment by rlei-weta** [comment] 2023-06-26 05:25
Hi @myartings, can you set `TF_DEBUG` environment variable to "*" prior to launching `usdview`, then copying & attaching the logged output here?  Thanks!

**Comment by myartings** [comment] 2023-06-26 06:07
@rlei-weta Here is the log.
[log.txt](https://github.com/wetadigital/USDPluginExamples/files/11864276/log.txt)

**Comment by rlei-weta** [comment] 2023-06-26 07:19
Much appreciated @myartings - it looks like the usdTriImaging.dll plugin was loaded but not in a good state.  I will find access to a Windows machine to try and repro this -- will touch base soon

**Comment by rlei-weta** [comment] 2023-07-02 00:56
@myartings wanted to give you a heads up that I was able to reproduce the issue you were seeing on Windows.  I don't know what the root problem is yet so will need to investigate.  Thanks for your patience!

**Comment by rlei-weta** [comment] 2023-07-02 01:28
Hi @myartings I've merged #45 into main which should fix the issue you are seeing (thanks @OleksiyPuzikov for the suggestion).  Let me know how that goes

**Closed as completed** 2024-04-17 02:26 UTC
